name: Gradle build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  gradle:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: gradle/wrapper-validation-action@v1
    - uses: actions/setup-java@v2
      with:
        distribution: temurin
        java-version: 11
        cache: gradle
        
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
    
    - name: Execute Gradle build for DNA
      run: ./gradlew build
    
    - name: Execute Gradle build for rDNA
      run: ./gradlew packageBuild
    
    - name: Store artifacts
      uses: actions/upload-artifact@v3
      with:
        name: DNA
        path: |
          dna/build/libs
          sample/sample.dna
          *.tar.gz

    - name: Execute Gradle rDNA check
      run: ./gradlew packageCheck
      
    - name: Execute Gradle rDNA test
      run: ./gradlew test
